apply plugin: "com.gradleup.shadow"
apply plugin: "me.modmuss50.mod-publish-plugin"

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    injectAccessWidener(tasks.named('jar'))
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content { includeGroup "maven.modrinth" }
    }
}

dependencies {
    api "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    compileOnly("maven.modrinth:modmenu:${rootProject.mod_menu_version}") { transitive false }

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    exclude "architectury.common.json"

    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    zip64 = true
    from rootProject.file("LICENSE.md")
}

assemble.dependsOn shadowJar

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

sourcesJar {
    afterEvaluate {
        def depSources = project(":common").sourcesJar
        dependsOn depSources
        from(depSources.archiveFile.map { zipTree(it) }) {
            exclude "architectury.accessWidener"
        }
    }
}

components.java {
    addVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {}
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archivesBaseName + "-fabric"
            from components.java
        }
    }

    repositories {
        if (System.getenv("MAVEN_PASS") != null) {
            maven {
                url = "https://deploy.shedaniel.me/"
                credentials {
                    username = "shedaniel"
                    password = System.getenv("MAVEN_PASS")
                }
            }
        }
    }
}

publishMods {
    file = shadowJar.archiveFile
    displayName = "[Fabric $rootProject.supported_version] v$project.version"
    changelog = releaseChangelog()
    modLoaders.add("fabric")

    var releaseType = ["release": STABLE, "beta": BETA, "alpha": ALPHA][rootProject.artifact_type]
    if (releaseType == null) throw new GradleException("Unknown artifact_type: $rootProject.artifact_type")
    type = releaseType

    var CURSE_API_KEY = project.findProperty("CURSE_API_KEY") ?: System.getenv("CURSE_API_KEY")
    if (CURSE_API_KEY != null) {
        curseforge {
            accessToken = CURSE_API_KEY
            projectId = rootProject.curseforge_id
            minecraftVersions.add(rootProject.minecraft_version)
            javaVersions.add(JavaVersion.VERSION_25)
            client = true
            server = true
            requires("fabric-api")
        }
    }

    var MODRINTH_TOKEN = project.findProperty("MODRINTH_TOKEN") ?: System.getenv("MODRINTH_TOKEN")
    if (MODRINTH_TOKEN != null) {
        modrinth {
            accessToken = MODRINTH_TOKEN
            projectId = rootProject.modrinth_id
            version = "$project.version+$project.name"
            minecraftVersions.add(rootProject.minecraft_version)
            requires("fabric-api")
        }
    }
}
