org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

platforms=fabric,neoforge

minecraft_version=26.2
supported_version=26.2

artifact_type=release

archives_base_name=architectury
archives_base_name_snapshot=architectury-snapshot
base_version=21.0
maven_group=dev.architectury
version_suffix=

fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.2
mod_menu_version=20.0.0-alpha.1

neoforge_version=26.2.0.0-beta

# Set to empty if not snapshots
neoforge_pr=

curseforge_id=419699
modrinth_id=lhGA9TYQ

loom.ignoreDependencyLoomVersionValidation=true
